language: node_js
node_js:
  - '9'
  - '10'
  - '11'
  - 'lts/*'
before_install:
  - npm install -g yo
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-brei-next' ]; then cd .. && eval "mv $currentfolder generator-brei-next" && cd generator-brei-next; fi
before_script:
  - npm install -g yo
deploy:
  provider: npm
  email: nessthehero@gmail.com
  api_key:
    secure: PW2nKCrW27DaGn9PREJDLmJcuecpUPFP2lgZ+9AcgQv9qF3v8QdZ675akj4xdfOCCQ1BAk2g1kyZkeXmLR7P5Fs7JnGY1UqjfoBn2BnbOMO1/I1Mt9Z0rRYXT2oUIYV2w4zFLrK9nEkjLX4pmZEneroyRxNy1Z8B31mO12ZJ+fU=
  on:
    tags: true
    repo: BarkleyREI/experimental-brei-app
